package com.udea.persistencia;
// Generated 6/12/2018 11:14:18 AM by Hibernate Tools 4.3.1


import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clima generated by hbm2java
 */
@Entity
@Table(name="clima"
    ,catalog="climaws"
)
public class Clima  implements java.io.Serializable {


     private Integer codigo;
     private String ciudad;
     private String clima;
     private int centigrados;
     private int fahrenheit;
     private int porcentajeHumedad;
     private int nubosidad;
     private int probPrecipitacion;
     private String prediccion;

    public Clima() {
    }

    public Clima(String ciudad, String clima, int centigrados, int fahrenheit, int porcentajeHumedad, int nubosidad, int probPrecipitacion, String prediccion) {
       this.ciudad = ciudad;
       this.clima = clima;
       this.centigrados = centigrados;
       this.fahrenheit = fahrenheit;
       this.porcentajeHumedad = porcentajeHumedad;
       this.nubosidad = nubosidad;
       this.probPrecipitacion = probPrecipitacion;
       this.prediccion = prediccion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="codigo", unique=true, nullable=false)
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="ciudad", nullable=false)
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    
    @Column(name="clima", nullable=false)
    public String getClima() {
        return this.clima;
    }
    
    public void setClima(String clima) {
        this.clima = clima;
    }

    
    @Column(name="centigrados", nullable=false)
    public int getCentigrados() {
        return this.centigrados;
    }
    
    public void setCentigrados(int centigrados) {
        this.centigrados = centigrados;
    }

    
    @Column(name="fahrenheit", nullable=false)
    public int getFahrenheit() {
        return this.fahrenheit;
    }
    
    public void setFahrenheit(int fahrenheit) {
        this.fahrenheit = fahrenheit;
    }

    
    @Column(name="porcentaje_humedad", nullable=false)
    public int getPorcentajeHumedad() {
        return this.porcentajeHumedad;
    }
    
    public void setPorcentajeHumedad(int porcentajeHumedad) {
        this.porcentajeHumedad = porcentajeHumedad;
    }

    
    @Column(name="nubosidad", nullable=false)
    public int getNubosidad() {
        return this.nubosidad;
    }
    
    public void setNubosidad(int nubosidad) {
        this.nubosidad = nubosidad;
    }

    
    @Column(name="prob_precipitacion", nullable=false)
    public int getProbPrecipitacion() {
        return this.probPrecipitacion;
    }
    
    public void setProbPrecipitacion(int probPrecipitacion) {
        this.probPrecipitacion = probPrecipitacion;
    }

    
    @Column(name="prediccion", nullable=false)
    public String getPrediccion() {
        return this.prediccion;
    }
    
    public void setPrediccion(String prediccion) {
        this.prediccion = prediccion;
    }

    @Override
    public String toString() {
        return "Clima{" + "codigo=" + codigo
                + ", ciudad=" + ciudad
                + ", clima=" + clima
                + ", centigrados=" + centigrados 
                + ", fahrenheit=" + fahrenheit 
                + ", porcentajeHumedad=" + porcentajeHumedad 
                + ", nubosidad=" + nubosidad 
                + ", probPrecipitacion=" + probPrecipitacion 
                + ", prediccion=" + prediccion + '}';
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 23 * hash + Objects.hashCode(this.codigo);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Clima other = (Clima) obj;
        if (!Objects.equals(this.codigo, other.codigo)) {
            return false;
        }
        return true;
    }




}


